spring:
  application:
    name: FX Deals Data Warehouse

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:15432}/${DB_NAME:fx-deals-warehouse}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
